apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: services
  name: cray-vpa-watcher-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-vpa-watcher-crb
subjects:
  - kind: ServiceAccount
    name: cray-vpa-watcher-sa
    namespace: services
roleRef:
  kind: ClusterRole
  name: cray-vpa-watcher-cr
  apiGroup: ""
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-vpa-watcher-cr
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["", "batch"]
    resources: ["jobs"]
    verbs: ["get", "list"]
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
    - restricted-transition-net-raw