#
# MIT License
#
# (C) Copyright 2024-2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Default values for cray-vpa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

vpa:
  recommender:
    image:
      repository: "artifactory.algol60.net/csm-docker/stable/registry.k8s.io/autoscaling/vpa-recommender"
      tag: 1.3.0
  admissionController:
    # Admission Controller is disabled, since it was disabled by default in previous cray-vpa version.
    # If we want to enable, the following flags will need to be added to the kube-apiserver manifest:
    #   --admission-control=MutatingAdmissionWebhook
    #   --runtime-config=admissionregistration.k8s.io/v1beta1=true
    enabled: false
    certGen:
      # Admission Controller uses kube-webhook-certgen to generate certs.
      image:
        repository: "artifactory.algol60.net/csm-docker/stable/registry.k8s.io/ingress-nginx/kube-webhook-certgen"
        tag: v1.5.2
    image:
      repository: "artifactory.algol60.net/csm-docker/stable/registry.k8s.io/autoscaling/vpa-admission-controller"
      tag: 1.3.0
  updater:
    image:
      repository: "artifactory.algol60.net/csm-docker/stable/registry.k8s.io/autoscaling/vpa-updater"
      tag: 1.3.0
  tests:
    image:
      repository: "artifactory.algol60.net/csm-docker/stable/docker-kubectl"
      tag: 1.32.2
